export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REM_ITEM = 'CART_REM_ITEM';
export const CART_SAVE_ADDRESS = 'CART_SAVE_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
